### PR TITLE
Add react support to eslint

### PR DESCRIPTION
**Pull request by FoRVaiS**
### Summary
1. Installed React ESLint plugin
2. Configured support for linting tsx with Typescript and React rules
3. Enabled tsx linting in frontend

### Testing
1. Verify tsx linting is working by opening `/apps/frontend/src/index.tsx`, you should see the following errors:
image

2. Verify React linting is working by forcing a "no duplicate properties" error on any React component:
```tsx
<App
  propA="Apply"
  propA="Apple" // No duplicates props allowed [react/jsx-no-duplicate-props]
/>
```

### CODE REVIEW

**Comment by FoRVaiS** [comment]
Worked: 0.5hrs

**Comment by toco-t** [comment]
I'm getting the following error: `Cannot find module '@typescript-eslint/utils' or its corresponding type declarations.ts(2307)` but this module is definitely installed...

image

**Comment by FoRVaiS** [comment]
> I'm getting the following error: `Cannot find module '@typescript-eslint/utils' or its corresponding type declarations.ts(2307)` but this module is definitely installed...
> image

That's a non-issue, just very annoying to look at. I already have a fix, too lazy to actually push it :)

They've deprecated the ESLint config interface since I last wrote that config and moved it elsewhere, deeper into package.

**Review by toco-t — APPROVED** [review]
Verified changes! Should be merged after [#52](https://github.com/Geek-Collectors-Network/geek-collectors-network/issues/52) to see the effect.

**Pull request merged**
